apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-container
        image: us-central1-docker.pkg.dev/innate-legacy-449121-a5/github-actions-repo/my_node_app:v1
        ports:
        - containerPort: 3030
