name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "Tests runned."

      - name: Build Docker image
        run: docker build -t my-node-app .

      - name: Scan Docker image with Trivy for vulnerabilities
        run: |
          # Install Trivy
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.tar.gz | tar -xzv
          sudo mv trivy /usr/local/bin/

          # Run Trivy scan on the Docker image
          trivy image --exit-code 1 --severity HIGH,CRITICAL my-node-app || true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.8
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use GCR
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Tag Docker image
        run: |
          docker tag my-node-app us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/github-actions-repo/my_node_app:v1

      - name: Push Docker image to GCR
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/github-actions-repo/my_node_app:v1

      - name: Install Google Cloud SDK (alternative)
        run: |
          echo "Installing Google Cloud SDK"
          curl -sSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /etc/apt/trusted.gpg.d/google.asc
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/google.asc] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk

      - name: Install GKE Authentication Plugin
        run: |
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Configure kubectl to interact with GKE
        run: |
            gcloud container clusters get-credentials my-cluster --zone us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f kubernetes/deployment.yaml  # Or the correct path to your deployment.yaml
          kubectl rollout status deployment/my-deployment